# Generated by Django 5.2.6 on 2025-09-26 19:05

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        db_column="title_en",
                        help_text="Article title in English",
                        max_length=500,
                    ),
                ),
                (
                    "title_it",
                    models.CharField(
                        blank=True,
                        db_column="title_it",
                        help_text="Article title in Italian",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "scraped_date",
                    models.DateTimeField(
                        blank=True,
                        db_column="scraped_date",
                        help_text="Date and time when the article was scraped",
                        null=True,
                    ),
                ),
                (
                    "llm_model",
                    models.TextField(
                        blank=True,
                        db_column="llm_model",
                        help_text="LLM model used for translation",
                        null=True,
                    ),
                ),
                (
                    "content_en",
                    models.TextField(
                        db_column="content_en",
                        help_text="Full article content in English",
                    ),
                ),
                (
                    "content_it",
                    models.TextField(
                        blank=True,
                        db_column="content_it",
                        help_text="Full article content in Italian",
                        null=True,
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        blank=True,
                        db_column="sector",
                        help_text="Sector of the article",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "article_date",
                    models.DateTimeField(
                        blank=True,
                        db_column="article_date",
                        help_text="Original publication date of the article",
                        null=True,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        db_column="url",
                        help_text="Original article URL",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        db_column="source",
                        help_text="The source of the article",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "validated",
                    models.BooleanField(
                        db_column="validated",
                        default=False,
                        help_text="Whether the article has been validated",
                    ),
                ),
                (
                    "time_translated",
                    models.DateTimeField(
                        blank=True,
                        db_column="time_translated",
                        help_text="Date and time when the article was translated",
                        null=True,
                    ),
                ),
                (
                    "used",
                    models.BooleanField(
                        db_column="used",
                        default=False,
                        help_text="Whether the article has been used",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "db_table": "articles",
                "ordering": ["-scraped_date"],
                "managed": False,
            },
        ),
    ]
