# Generated by Django 5.2.6 on 2025-09-27 17:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "managed": True,
                "ordering": ["-scraped_date"],
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
            },
        ),
    ]
