# Generated by Django 5.2.6 on 2025-09-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'managed': False, 'ordering': ['-scraped_date'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
