# Generated by Django 5.2.6 on 2025-10-04 06:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0004_weeklysummary"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "managed": False,
                "ordering": ["-scraped_at"],
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
            },
        ),
    ]
