services:
  # MongoDB database with vector search support (8.2+)
  mongodb:
    image: mongodb/mongodb-community-server:8.2-ubuntu2404
    container_name: ta_mongodb
    ports:
      - "7587:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=analyst
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  # MongoDB Search Service (mongot)
  mongot:
    image: mongodb/mongodb-atlas-search:8.2.0
    container_name: ta_mongot
    ports:
      - "27027:27027"
    environment:
      - MONGOT_MONGOD_HOST_AND_PORT=mongodb:27017
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped

  # Redis cache and message broker
  redis:
    image: redis:7-alpine
    container_name: ta_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Django web application
  web:
    build: .
    container_name: ta_web
    command: >
      sh -c "python manage.py download_models &&
             gunicorn analyst.wsgi:application --bind 0.0.0.0:8000 --workers 4 --timeout 120"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - sentence_transformers_cache:/root/.cache/torch/sentence_transformers
      - huggingface_cache:/root/.cache/huggingface
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DB_HOST=mongodb
      - DB_PORT=27017
      - MONGODB_URI=mongodb://mongodb:27017/?directConnection=true
    depends_on:
      mongodb:
        condition: service_healthy
      mongot:
        condition: service_started
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Celery worker for background tasks
  celery_worker:
    build: .
    container_name: ta_celery_worker
    command: >
      sh -c "python manage.py download_models &&
             celery -A analyst worker --loglevel=info --concurrency=1 --pool=solo"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - .:/app
      - sentence_transformers_cache:/root/.cache/torch/sentence_transformers
      - huggingface_cache:/root/.cache/huggingface
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DB_HOST=mongodb
      - DB_PORT=27017
      - MONGODB_URI=mongodb://mongodb:27017/?directConnection=true
    depends_on:
      mongodb:
        condition: service_healthy
      mongot:
        condition: service_started
      redis:
        condition: service_healthy
    restart: unless-stopped

  # Celery beat for scheduled tasks
  celery_beat:
    build: .
    container_name: ta_celery_beat
    command: celery -A analyst beat --loglevel=info
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - .:/app
      - sentence_transformers_cache:/root/.cache/torch/sentence_transformers
      - huggingface_cache:/root/.cache/huggingface
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DB_HOST=mongodb
      - DB_PORT=27017
      - MONGODB_URI=mongodb://mongodb:27017/?directConnection=true
    depends_on:
      mongodb:
        condition: service_healthy
      mongot:
        condition: service_started
      redis:
        condition: service_healthy
      web:
        condition: service_started
    restart: unless-stopped

volumes:
  mongodb_data:
  redis_data:
  static_volume:
  media_volume:
  sentence_transformers_cache:
  huggingface_cache:

networks:
  default:
    name: ta_network
